apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkindeployment
spec:
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          resources:
            requests:
              memory: 1024Mi
              cpu: 50m
            limits:
              memory: 2048Mi
              cpu: 200m
          ports:
            - containerPort: 9411