apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-auth
  labels:
    app: authdeployment
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth
        image: javaboost2/java3auth:v004
        resources:
          requests:
            memory: 1024Mi
            cpu: 100m
          limits:
            memory: 2048Mi
            cpu: 200m
        ports:
        - containerPort: 9090
        env:
        - name: secretkey
          value: "AdminBilge"
        - name: audience
          value: "bilgeadam"
        - name: issuer
          value: "bilgeadam"