apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-config
  labels:
    app: configdeployment
spec:
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config
        image: javaboost2/java3config:v004
        resources:
          requests:
            memory: 1024Mi
            cpu: 100m
          limits:
            memory: 2048Mi
            cpu: 200m
        ports:
        - containerPort: 8888
        env:
        - name: secretkey
          value: "AdminBilge"
        - name: audience
          value: "bilgeadam"
        - name: issuer
          value: "bilgeadam"