apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-main
  labels:
    app: maindeployment
spec:
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
      - name: main
        image: javaboost2/java3main:v001
        resources:
          requests:
            memory: 1024Mi
            cpu: 100m
          limits:
            memory: 2048Mi
            cpu: 200m
        ports:
        - containerPort: 9091
        env:
        - name: secretkey
          value: "AdminBilge"
        - name: audience
          value: "bilgeadam"
        - name: issuer
          value: "bilgeadam"