apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-user
  labels:
    app: userdeployment
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user
        image: javaboost2/java3user:v002
        resources:
          requests:
            memory: 1024Mi
            cpu: 150m
          limits:
            memory: 2048Mi
            cpu: 200m
        ports:
        - containerPort: 9092
        env:
        - name: secretkey
          value: "AdminBilge"
        - name: audience
          value: "bilgeadam"
        - name: issuer
          value: "bilgeadam"