apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgredeployment
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgredb
          image: postgres
          resources:
            requests:
              memory: 1024Mi
              cpu: 250m
            limits:
              memory: 2048Mi
              cpu: 500m
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "root"
