apiVersion: v1
kind: Service
metadata:
  name: clusterip-config
  labels:
    app: configservice
spec:
    ports:
    - port: 8888
      targetPort: 8888
    selector:
      app: config-service
    type: ClusterIP