apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-main
  labels:
    app: mainservice
spec:
    ports:
    - port: 9091
      targetPort: 9091
    selector:
        app: main-service
    type: LoadBalancer