apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-user
  labels:
    app: userservice
spec:
    ports:
    - port: 9092
      targetPort: 9092
    selector:
        app: user-service
    type: LoadBalancer