server:
  port: 9090

spring:
  rabbitmq:
    host: 10.64.0.21
    port: 5672
    username: bilgeadmin
    password: bilge!
  zipkin:
    enabled: true
    base-url: http://10.64.0.18:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.64.0.12:5432/java3auth
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


myapplication:
  auth-service:
    feign-client: http://10.68.12.147:9090/api/v1
  main-service:
    feign-client: http://10.68.13.16:9091/api/v1
  user-service:
    feign-client: http://10.68.13.95:9092/api/v1

# JWT
myjwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}