server:
  port: 10900

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: bilgeadmin
    password: bilge!
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service

myapplication:
  auth-service:
    feign-client: http://10.68.12.147:9090/api/v1
  main-service:
    feign-client: http://10.68.13.16:9091/api/v1
  user-service:
    feign-client: http://10.68.13.95:9092/api/v1

# JWT
myjwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}