server:
  port: 9091

spring:
  security:
    user:
      name: muhammet
      password: 123456
  data:
    mongodb:
      host: 34.70.190.164
      port: 27777
      database: java3yarisma
      username: bilgeuser
      password: "bilge!!**"
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service


myredis:
    host: localhost
    port: 6379

myapplication:
  auth-service:
    url: http://localhost:9090/api/v1
  user-service:
    feign-client: http://localhost:9092/api/v1
  elastic-service:
    feign-client: http://localhost:9099/api/v1/elastic

# JWT
myjwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}